### PR TITLE
Create Enormous Input Test.cpp

### PR DESCRIPTION
**Pull request by kmryashasvi**
## Related Issue
Solved issue number: #206

added solution to the problem "Enormous Input Test" listed on codechef

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Follow pull request template.

**Comment by kmryashasvi** [comment]
> Follow pull request template.

Please recheck @Nivedita967

**Comment by kmryashasvi** [comment]
Is it now okay?

**Comment by Nivedita967** [comment]
Yes, all do follow for all pull request.

**Comment by Nivedita967** [comment]
You have documented your code. So check all the checkboxes and it is possible to commit "Enormous Input Test.c" in this pull request itself.

**Comment by kmryashasvi** [comment]
> You have documented your code. So check all the checkboxes and it is possible to commit "Enormous Input Test.c" in this pull request itself which belongs to same issue.

It will not happen again @Nivedita967

**Pull request merged**
