### PR TITLE
Minimum insertion for pallindrome

### PR DESCRIPTION
**Pull request by Amit366**
## Related Issue
Closes: #722 

### Describe the changes you've made
Algorithm for finding Minimum insertion for pallindrome

### Language used for coding
C

### CODE REVIEW

**Comment by Nivedita967** [comment]
There is one extra file added, please remove.

**Comment by Amit366** [comment]
@Nivedita967 check now..

**Comment by Nivedita967** [comment]
Make sure your code passes all the test cases on the platform (leetcode).

**Comment by Amit366** [comment]
@Nivedita967 there are 3 more PRs. Please review them. It's been 2 days

**Comment by Amit366** [comment]
I will check it and make the changes for this

**Comment by Nivedita967** [comment]
> @Nivedita967 there are 3 more PRs. Please review them. It's been 2 days

I will, but this commit is common in all pull request, that's why.

**Comment by Amit366** [comment]
@Nivedita967 i have removed it from all. Once check

**Pull request closed without merging**
