### PR TITLE
Create Plus Minus.py

### PR DESCRIPTION
**Pull request by JASKAMAL22**
## Related Issue
Closes: #542 

### Describe the changes you've made
added source add with a little description

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Python

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by JASKAMAL22** [comment]
Kindly review it and please let me know if any modification is required!  :)

**Comment by Nivedita967** [comment]
@JASKAMAL22 You are assigned to previous issues #477 and #476. You are not responding in the comments too. Are you working on them or not?

**Comment by JASKAMAL22** [comment]
Sorry for rate reply!!
Yes I am working on those

**Comment by Nivedita967** [comment]
> Sorry for rate reply!!
> Yes I am working on those

Okay.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
