### PR TITLE
Staircase

### PR DESCRIPTION
**Pull request by JASKAMAL22**
## Related Issue
Closes: #543 
Closes: #537 
Closes: #509 

### Describe the changes you've made
simple codes of three particular problems stated above with comments .

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Python

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by JASKAMAL22** [comment]
Hello @Nivedita967 , I open this pull request for Staircase problem . Please ignore rest files. Can you please tell how to resolve problem of having multiple file's solution in a single pull request. :)

**Comment by JASKAMAL22** [comment]
I write the issue numbers of three problems for which the above file associates. Is it right?

**Comment by Nivedita967** [comment]
> I write the issue numbers of three problems for which the above file associates. Is it right?

Yes, this is okay. But before committing new solution, create new branch and work on it. Means you have to create separate branches for separate issues.

**Comment by JASKAMAL22** [comment]
ok thankyou!!

**Comment by JASKAMAL22** [comment]
Will this pull request be considered or not ?

**Comment by Nivedita967** [comment]
Yes, this will be considered.

**Pull request merged**
