### PR TITLE
Solved issue#26 Subsets

### PR DESCRIPTION
**Pull request by greenblade29**

### CODE REVIEW

**Comment by Nivedita967** [comment]
Can you please work on C or Python ?

**Comment by Mahindra-7** [comment]
@Nivedita967 small doubt
should i need to make a note of the issue number and pull request which i solved or is there excel sheet for the contributors?

**Comment by greenblade29** [comment]
> Can you please work on C or Python ?

I can work on C++

**Comment by Nivedita967** [comment]
> @Nivedita967 small doubt
> should i need to make a note of the issue number and pull request which i solved or is there excel sheet for the contributors?

No, you just contribute to different projects. These thing is done by Organizer of CrossWoc

**Comment by Mahindra-7** [comment]
@Nivedita967  Thankyou for solving my doubt

**Comment by Nivedita967** [comment]
@greenblade29 Can you work on else issue because only C and Python is remaining in this issue.

**Comment by Nivedita967** [comment]
> @Nivedita967 Thankyou for solving my doubt

You should join Gitter channel - https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community for any queries and all.

**Pull request closed without merging**
