### PR TITLE
Add Closest Dessert Cost in python

### PR DESCRIPTION
**Pull request by muthuannamalai12**
## Related Issue
Closes: #688 issue number that will be closed through this PR

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I have added the implementation of Closest Desert COst Problem
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
### Language used for coding
Mention the language you have used for coding here.
Python
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
@muthuannamalai12 Please add some comments to your code so that beginners can understand it easily.

**Comment by Nivedita967** [comment]
@muthuannamalai12 Add comments to your code in all your PR.

**Comment by muthuannamalai12** [comment]
@Nivedita967 Sorry for not responding For a long time. I had my exams Now I have updated it

**Comment by Nivedita967** [comment]
> @Nivedita967 Sorry for not responding For a long time. I had my exams Now I have updated it

No problem :)

**Pull request merged**
