### PR TITLE
added removing duplicates in an array

### PR DESCRIPTION
**Pull request by Sloth-Panda**
## Related Issue
Solved issue number: #[issue number that will be closed through this PR]
#100 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
added java code for removing duplicates in an array

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Language used for coding
Mention the language you have used for coding here.
Java
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@Nivedita967  can you please check this pr and assign me other issues that I raised I actually forgot I was assigned this. Thank You!

**Comment by Nivedita967** [comment]
your folder name should be the exact name of the problem as on the coding platform which is "Remove Duplicates from Sorted Array".
So change your folder name from `"duplicate_in_array" -> "Remove Duplicates from Sorted Array"`

**Comment by Sloth-Panda** [comment]
@Nivedita967 have changed it

**Comment by Nivedita967** [comment]
don't include your language in the folder.

**Comment by Sloth-Panda** [comment]
@Nivedita967 its not allowing cause someone has  already added the folder  with the same name so should I delete my folder and add the code in that folder ??

**Comment by Nivedita967** [comment]
Yes, you have to add your code to the existing folder. Each problems has one folder and under that folder different language code will be include. That's why I have told you to name the folder exactly as the same name on coding platform.

**Comment by Sloth-Panda** [comment]
@Nivedita967 can you add tags to this issue

**Comment by Nivedita967** [comment]
what tags? where to add ?

**Comment by Sloth-Panda** [comment]
@Nivedita967 I  was confused about it . Have chnagd it location though

**Comment by Nivedita967** [comment]
Great :)

**Pull request merged**
