### PR TITLE
Maximum subarray

### PR DESCRIPTION
**Pull request by Amit366**
## Related Issue
Closes: #250 

### Describe the changes you've made
Algorithm for Maximum subarray

### Language used for coding
Java

### CODE REVIEW

**Comment by Nivedita967** [comment]
@Amit366 Your folder name should be same as the problem name which is "Maximum Subarray Sum" not "Maximum subarray sum".

**Comment by Amit366** [comment]
@Nivedita967 it was already present

**Comment by Amit366** [comment]
I haven't changed or created the folder

**Comment by Nivedita967** [comment]
I have made changes, please pull the changes once.

**Comment by Amit366** [comment]
@Nivedita967 I am getting this error on pulling the repo:

CONFLICT (file location): Hackerrank/Maximum subarray sum/Maximum_subarray.java added in HEAD inside a directory that was renamed in 9f35cf5b8c12d4cb7ee69f5c7a2b13586317204b, suggesting it should perhaps be moved to Hackerrank/Maximum Subarray Sum/Maximum_subarray.java.
Automatic merge failed; fix conflicts and then commit the result.

**Comment by Amit366** [comment]
@Nivedita967 I have sent another PR . So I am closing this one.

**Pull request closed without merging**
