### PR TITLE
Printing Pattern Using Loops

### PR DESCRIPTION
**Pull request by saimanoharhm**
## Related Issue
Solved issue number: #428

### Describe the changes you've made
I have added code for printing pattern using c.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
c

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have documented the code.
- [ x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by saimanoharhm** [comment]
@Nivedita967 I have added code for printing pattern using c.

**Comment by Nivedita967** [comment]
Your folder name should be same as the name of problem on platform.
For this PR, name of the problem on platform is "Printing Pattern Using Loops".
So update your folder name `Printing_Pattern_Using_Loops` -> `Printing Pattern Using Loops`.
Also add some comments in your code so that beginners can understand it easily.

**Comment by saimanoharhm** [comment]
@Nivedita967 Could you pls check my PR and let me know if you need further changes.

**Comment by Nivedita967** [comment]
@saimanoharhm Not the pull request name. I am asking to change your folder name which you have given the name as "Printing_Pattern_Using_Loops"

**Comment by saimanoharhm** [comment]
> @saimanoharhm Not the pull request name. I am asking to change your folder name which you have given the name as "Printing_Pattern_Using_Loops"

@Nivedita967  I have sent a msg in gitter chat regarding this. Could you pls check.

**Comment by saimanoharhm** [comment]
@Nivedita967 Could you pls check it now.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
