### PR TITLE
Longest Substring problem

### PR DESCRIPTION
**Pull request by JASKAMAL22**
## Related Issue
Solved issue number: #537 

### Describe the changes you've made
source code of the leetcode problem with a little description

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Python

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Have you solved two issues in one?

**Comment by JASKAMAL22** [comment]
No I do them separately and both have different pull request.

**Comment by JASKAMAL22** [comment]
I think it shows both of them in a single request. Now what to do next!  :)

**Comment by Nivedita967** [comment]
Mention the second issue number here itself.

**Comment by Nivedita967** [comment]
But @JASKAMAL22 every time try to add commits in different branches. This will be helpful :)

**Pull request closed without merging**
