### PR TITLE
Sum of elements in the array

### PR DESCRIPTION
**Pull request by chiragagrawal9200**
Created C and C++ program to print sum of elements in an array

## Related Issue
Closes: #692 

### Describe the changes you've made
I have added c++ and c files

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C and C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
@chiragagrawal9200 You should work on C++ only. I just said that C and C++ are almost same. You were assigned for C++ only.

**Comment by chiragagrawal9200** [comment]
> @chiragagrawal9200 You should work on C++ only. I just said that C and C++ are almost same. You were assigned for C++ only.

Yes I did it using C++ @Nivedita967

**Comment by chiragagrawal9200** [comment]
> @chiragagrawal9200 You should work on C++ only. I just said that C and C++ are almost same. You were assigned for C++ only.

I will delete the C file if you want @Nivedita967 . Then you can merge this pr?

**Comment by Nivedita967** [comment]
Sure remove C file :)

**Comment by chiragagrawal9200** [comment]
> Sure remove C file :)
please see now @Nivedita967

**Comment by chiragagrawal9200** [comment]
@Nivedita967 please see now

**Comment by Nivedita967** [comment]
@abhinav5481 Your folder name should be same as problem name on platform which is "1D Arrays in C".
So change your folder name to `sum of elements in the array` to `1D Arrays in C`
You can read [Contribution Guidelines](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/.github/contributing.md)

**Comment by chiragagrawal9200** [comment]
> @chiragagrawal9200 Your folder name should be same as problem name on platform which is "1D Arrays in C".
> So change your folder name to `sum of elements in the array` to `1D Arrays in C`
> You can read [Contribution Guidelines](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/.github/contributing.md)

Done! @Nivedita967

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
