### PR TITLE
fix: deleted second largest.c

### PR DESCRIPTION
**Pull request by kmryashasvi**
because i have moved it in a directory

### CODE REVIEW

**Comment by Nivedita967** [comment]
but you are deleting that directory "second largest.c" file.

**Comment by kmryashasvi** [comment]
i'm not deleting the directory
i am deleting the file
which is without any folder in the codechrf directory

**Comment by Nivedita967** [comment]
Okay.

**Comment by Nivedita967** [comment]
This project is now under [CrossWoC](https://crosswoc.ieeedtu.in/). If you want to contribute to this project, you can join the this program [CrossWoC](https://crosswoc.ieeedtu.in/) as a participant.

**Pull request merged**
