### PR TITLE
Reverse linked list Iteratively in C++

### PR DESCRIPTION
**Pull request by ishikabansal04**
## Related Issue
Solved issue number: #102 

### Describe the changes you've made
Adding source code for Reversing A LinkedList Without Recursion (Iteratively in C++)

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by ishikabansal04** [comment]
Please review my code for Reverse Linked List Without Recursion ;-)

**Comment by Nivedita967** [comment]
Folder name should be `Reverse Linked List` only. Use the exact name as on the coding platform.

**Comment by ishikabansal04** [comment]
> Folder name should be `Reverse Linked List` only. Use the exact name as on the coding platform.

Sure . I'll correct it :)

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
