### PR TITLE
Target Sum(Java and C++) and House Robber(C++ Solution)

### PR DESCRIPTION
**Pull request by greenblade29**
Issue #73

### CODE REVIEW

**Comment by Nivedita967** [comment]
You have added two solutions.

**Comment by greenblade29** [comment]
Yeah I did create pull request for House robber only, but then I solved Target Sum also. You can wait till I add Target Sum solution in java ... and then you can resolve two issues in one merge

**Comment by greenblade29** [comment]
issues #112 and #73

**Comment by Nivedita967** [comment]
Create new pull request for java target sum. Try to solve different issues by creating different branches.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
