### PR TITLE
added pr template

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue-> #23 

@Nivedita967

### CODE REVIEW

**Comment by Nivedita967** [comment]
@Sloth-Panda  This is so long.
Please remove-
1. Type of change section
2. How Has This Been Tested? 
3. Screenshots section 
4. In checklist- 
> * Checklist 5
> * Checklist 6

In the first heading, the spelling of issues is wrong. Please check.

**Comment by Nivedita967** [comment]
@Sloth-Panda Have you solved this ?

**Comment by Sloth-Panda** [comment]
@Nivedita967 Yes making new commit in few minutes

**Comment by Sloth-Panda** [comment]
@Nivedita967 I have made the pr you can verify

**Comment by Nivedita967** [comment]
Please add one section for the language in which the contributor coded.

**Comment by Sloth-Panda** [comment]
done @Nivedita967

**Comment by Nivedita967** [comment]
You have created checklist for languages, but in every pull request, contributor will contribute in only one language mainly. So, I think, leave that section for writing language and remove checklist.

**Comment by Sloth-Panda** [comment]
check @Nivedita967

**Comment by Nivedita967** [comment]
Nice :) Thanx.

**Comment by Nivedita967** [comment]
Just one thing, In the section of language used, you have commented description.

**Comment by Sloth-Panda** [comment]
@Nivedita967

**Comment by Nivedita967** [comment]
Great :)

**Pull request merged**
