### PR TITLE
Solved and Added the Leetcode Subset, and Hackerrank Left Rotate Array Problem in Python

### PR DESCRIPTION
**Pull request by saksham-s1ngh**
Solved the medium difficulty subset problem from Leetcode in Python language. #26

### CODE REVIEW

**Comment by saksham-s1ngh** [comment]
Also Solved the Left Rotate array problem on Hackerrank, and created and added that code in Python as well.

**Comment by Nivedita967** [comment]
Screenshot (125)
Why have you commented 2nd line ?

**Comment by saksham-s1ngh** [comment]
> Screenshot (125)
> Why have you commented 2nd line ?

It was the original line on the Leetcode website, so I was unsure, whether to keep it or remove it. Should I just remove and do another commit?

**Comment by Nivedita967** [comment]
No, don't remove original lines.

**Comment by saksham-s1ngh** [comment]
Okay, I just decided to take out the function out of the class, since on Leetcode we just have to build the function, and we recieve the arguments by default.
But I needed to send the inputs, so I just made it a function without any class, to make it easier to understand.

**Comment by Nivedita967** [comment]
@saksham-s1ngh I am merging your pull request. Try to solve more issues :)

**Pull request merged**
