### PR TITLE
Bitwise operators

### PR DESCRIPTION
**Pull request by pri1311**
## Related Issue
Closes: #749 

### Describe the changes you've made
Added C++ solution to  BitwiseOperators

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have documented the code.
- [x ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
@pri1311 This is a problem of Hackerrank, you have sifted this in the leetcode folder.

**Comment by pri1311** [comment]
changing it

**Comment by pri1311** [comment]
@Nivedita967 Sorry for the issue, fixed it.

**Comment by Nivedita967** [comment]
> @Nivedita967 Sorry for the issue, fixed it.

No problem, please add comments to your code.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
