### PR TITLE
Adding source code along with description...

### PR DESCRIPTION
**Pull request by JASKAMAL22**
## Related Issue
Solved issue number: #354 

### Describe the changes you've made
code of the problem with a clear description

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Python

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Path of your file should be `Leetcode/Sqrt(x)/DSA_square_root.py`
Add your file "DSA_square_root.py" in a directory named "Sqrt(x)" which will be under directory of Leetcode.

**Comment by JASKAMAL22** [comment]
I added source file in the folder named "Sqrt(x)" under the leetcode directory. Please let me know if further change is required!!

**Comment by Nivedita967** [comment]
Nice, Always add your code file in the folder named same as problem name on coding platform, under respective coding platform.

**Comment by JASKAMAL22** [comment]
Ok.. Thankyou for your guidance :)

**Pull request merged**
