### PR TITLE
Tree- Huffman Decoding

### PR DESCRIPTION
**Pull request by Akash20x**
## Related Issue
Closes: #921 

### Describe the changes you've made
Add the solution of hackerrank problem in python 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Python 

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
@Akash20x Your code should pass the all test cases on hackerrank, but it is not.

**Comment by Akash20x** [comment]
OK i will check

**Comment by Nivedita967** [comment]
> OK i will check and update it

Have you checked this @Akash20x ?

**Comment by Akash20x** [comment]
I will correct it till 9:00 PM, as I am busy with pending issues

**Comment by Akash20x** [comment]
> > OK i will check and update it
> 
> Have you checked this @Akash20x ?

Yes

**Pull request merged**
