### PR TITLE
#96 created AddTwoNumbers.c

### PR DESCRIPTION
**Pull request by kmryashasvi**

### CODE REVIEW

**Comment by Nivedita967** [comment]
Do provide issue number in the comment.

**Comment by kmryashasvi** [comment]
#96 before the commit message is the issue number
image

**Comment by kmryashasvi** [comment]
this is regarding issue #96

**Comment by Nivedita967** [comment]
> #96 before the commit message is the issue number
> image

Yes, I noticed but try to add issue number in the comment.

**Comment by kmryashasvi** [comment]
> > #96 before the commit message is the issue number
> > image
> 
> Yes, I noticed but try to add issue number in the comment.

okay, I will consider it now

**Pull request merged**
