### PR TITLE
Leetcode-Sort integers by power value

### PR DESCRIPTION
**Pull request by pri1311**
## Related Issue
Closes: #773 

### Describe the changes you've made
Added C++ solution to Leetcode Problem no 1387. Sort Integers by The Power Value

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have documented the code.
- [ x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Your folder name should be same as Problem name on platform which is "Sort Integers by The Power Value"

**Comment by pri1311** [comment]
Hie. Sorry for that! Fixed it. Thank you @Nivedita967

**Comment by Nivedita967** [comment]
B should be small in the name, isn't it?

**Comment by pri1311** [comment]
Sorry again! Fixed it.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
