### PR TITLE
Source Code for Snakes & Ladders in C++

### PR DESCRIPTION
**Pull request by ishikabansal04**
## Related Issue
Solved issue number: #245

### Describe the changes you've made
Added the source code for Snakes & Ladders problem in C++.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
You have documented your code. So check the checkbox of *"I have made corresponding changes to the documentation."*

**Comment by ishikabansal04** [comment]
> You have documented your code. So check the checkbox for _"I have made corresponding changes to the documentation."_

Done @Nivedita967 . thankyou.

**Comment by Nivedita967** [comment]
Add some comments to your code for easy understanding for beginners.

**Comment by ishikabansal04** [comment]
> Add some comments to your code for easy understanding for beginners.

Sure I'll add. Just a doubt, after making the required changes do i have to create the PR again or the changes are directly reflected? Please help @Nivedita967

**Comment by Nivedita967** [comment]
Changes directly reflect here :)

**Comment by ishikabansal04** [comment]
> Changes directly reflect here :)

I have added the comments. Please review @Nivedita967

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
