### PR TITLE
Added Leetcode Problem

### PR DESCRIPTION
**Pull request by Akash20x**

### CODE REVIEW

**Comment by Akash20x** [comment]
Pull Request for issue #114

**Comment by Nivedita967** [comment]
Nice :) Just add some comments please.

**Comment by Akash20x** [comment]
Ok , I will do it

**Comment by Akash20x** [comment]
## Related Issuse or bug
  - This Pull request is related to 2 issues problems:
  - Rank Transform Of An Array
  - Shortest Path In Binary Matrix

Fixes:
#113 
#114 

#### Describe the changes you've made
Few files for the code of the above 2 leetcode problems in java

Problem Links:
https://leetcode.com/problems/shortest-path-in-binary-matrix/description/
https://leetcode.com/problems/rank-transform-of-an-array/description/

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

**Comment by Nivedita967** [comment]
Please add comment to both code.

**Comment by Akash20x** [comment]
As this is 1 pull request for both issues, above comment is common for both issues.

**Comment by Nivedita967** [comment]
No, add some comment lines in your code so that it will be easy to understand your code for beginners. 
You can check some code in this project itself.

**Comment by Nivedita967** [comment]
Now this is nice :)

**Pull request merged**
