### PR TITLE
Count Square Submatrices with All Ones.cpp

### PR DESCRIPTION
**Pull request by jayantjethi**
Count Square Submatrices with All Ones#326
## Related Issue
Solved issue number: #326

### Describe the changes you've made
Added Code For Count Square Submatrices with All Ones in cpp

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
c++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
You have solved two issues?
"Count Square Submatrices with All Ones" and "Sum And Differences of Two Numbers"

**Comment by jayantjethi** [comment]
> You have solved two issues?
> "Count Square Submatrices with All Ones" and "Sum And Differences of Two Numbers"

Mam Actually By Mistake i added second code its of some other question please consider my code for count square submatrices only its complete

**Comment by jayantjethi** [comment]
> You have solved two issues?
> "Count Square Submatrices with All Ones" and "Sum And Differences of Two Numbers"

But yes I have solved two issue one is of count square submatrices and sum and differences of two in single PR i have mentioned both Of them these two were assigned to me

**Comment by Nivedita967** [comment]
> > You have solved two issues?
> > "Count Square Submatrices with All Ones" and "Sum And Differences of Two Numbers"
> 
> But yes I have solved two issue one is of count square submatrices and sum and differences of two in single PR i have mentioned both Of them these two were assigned to me

No problem :)

**Comment by jayantjethi** [comment]
> > > You have solved two issues?
> > > "Count Square Submatrices with All Ones" and "Sum And Differences of Two Numbers"
> > 
> > 
> > But yes I have solved two issue one is of count square submatrices and sum and differences of two in single PR i have mentioned both Of them these two were assigned to me
> 
> No problem :) Just mention the issue number of "Sum And Differences of Two Numbers" also.

Mam Issue No. For count Square Submatrices is #326 
And Issue No. For Sum And Differences Of Two Numbers is #171 
Please Merge Both the Respective Files These both are coded in C++ Language

**Comment by jayantjethi** [comment]
Mam I have also Added File for Finding All Substring of a string i have commit here only in this PR 
Finding All Substring is my issue no. #302 So Basically i have resolved three Issues (with all the issue no.s Mentioned In the same PR itself ) Please merge them All Accordingly)

**Pull request merged**
