### PR TITLE
Added Day of the Programmer, merge tools, minion game

### PR DESCRIPTION
**Pull request by kavania2002**
Provided solution of #99 #101 #103 
Thanks for the opportunity, enjoy coding.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Can you please add comments for easy understanding for beginners.

**Comment by kavania2002** [comment]
Ohk sure. Good idea.

**Comment by kavania2002** [comment]
Corrected error for #126 also

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
