### PR TITLE
Source Code for Red Knight's Shortest Path in Java

### PR DESCRIPTION
**Pull request by ishikabansal04**
## Related Issue
Closes: #826 

### Describe the changes you've made
Adding code for Red Knight's Shortest Path in Java

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Language used for coding
Java

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
@ishikabansal04 No need to add space in import statements.

**Comment by ishikabansal04** [comment]
> @ishikabansal04 No need to add space in import statements.

Removed the spaces and updated the file. Please review.

**Comment by Nivedita967** [comment]
Screenshot (137)

Just one small change here. You have not removed space in first line.

**Comment by Nivedita967** [comment]
@ishikabansal04 Make changes so that I can review your next pull requests because this commit is common in all your pr.

**Comment by ishikabansal04** [comment]
> @ishikabansal04 Make changes so that I can review your next pull requests because this commit is common in all your pr.

I am really sorry for the inconvinience . I have removed that space.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
