### PR TITLE
XOR_operation

### PR DESCRIPTION
**Pull request by JASKAMAL22**
## Related Issue
Solved issue number: #25 

### Describe the changes you've made
Added source code of the problem with precise documentation.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Python

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Have you tested your code on Leetcode ?

**Comment by JASKAMAL22** [comment]
I check the given test cases . What next I have to do?

**Comment by Nivedita967** [comment]
You have to submit your code on leetcode and check if all the test cases passes or not.

**Comment by JASKAMAL22** [comment]
I had submitted the code on leetcode. Below is its updated source add. Kindly check it and tell if any change is required to do...

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
