### PR TITLE
Added #143 Balanced Bracket Code in java

### PR DESCRIPTION
**Pull request by Archna29**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Language used for coding
Mention the language you have used for coding here.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Hey, @Archna29 This issue template should be filled that asking you related issue, language used etc. If you satisfy the statements of checklists the check the checkboxes :)

**Comment by Archna29** [comment]
I have check

**Comment by Nivedita967** [comment]
Do mention issue number in the comment.

**Comment by Archna29** [comment]
#143

**Pull request merged**
