### PR TITLE
removing Duplicate

### PR DESCRIPTION
**Pull request by deeqakkk**
## Related Issue
  - removing duplicate elements from sorted array

Solved: #100 

### Describe the changes you've made
i had given a solution of this in C++.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by deeqakkk** [comment]
@Nivedita967  check my pull request .

**Comment by Nivedita967** [comment]
Your folder name is "Contains Duplicate" but always write folder name by the exact name of problem as on coding platform. Check that exact name is "Remove Duplicates from Sorted Array" rename your folder.

**Comment by deeqakkk** [comment]
@Nivedita967  check it now

**Comment by Nivedita967** [comment]
Now this is perfect :)

**Comment by deeqakkk** [comment]
thanks XD

**Pull request merged**
