### PR TITLE
Array Reversal

### PR DESCRIPTION
**Pull request by deephunt3r**
## Related Issue
Closes: #691 

### Describe the changes you've made
program to reverse the order of given array

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
- NA
### Language used for coding
- c
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
This should be inside the Hackerrank folder isn't it?

**Comment by deephunt3r** [comment]
> This should be inside the Hackerrank folder isn't it?

Yes. It is inside hackerrank folder

**Comment by Nivedita967** [comment]
No. Also your folder name is not correct. Please read [ Contribution Guidelines ](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/.github/contributing.md

**Comment by deephunt3r** [comment]
> No. Also your folder name is also not correct. Please read [Contribution Guidelines](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/.github/contributing.md)

Sorry I have made a mistake. Now I made the required changes you can have look at it.

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
