### PR TITLE
Add MaximiseFunction java code.

### PR DESCRIPTION
**Pull request by zenilharia26**
## Related Issue
Solved issue number: #117  

### Describe the changes you've made
Added the java code for Maximise Function problem of Codechef.  

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Language used for coding
Java

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Hey @zenilharia26 You have not read the pinned issue. That clearly says "Always get the issue assigned to you first, before working on that".

**Comment by Nivedita967** [comment]
I have closed that issue on which you are working. I am opening that issue again, please look for the issue 11 days ago and comment on that issue. After which I will assign you that issue and you have to mention that issue on this PR then only I can accept this PR.

**Comment by zenilharia26** [comment]
Alright, I may have misunderstood the sentence. I'll comment on that issue. 
Thank you!

**Comment by zenilharia26** [comment]
Hey @Nivedita967, I have mentioned the issue number in this PR. I have also added comments to my code. Please review it.

**Comment by Nivedita967** [comment]
Nice :)

**Comment by zenilharia26** [comment]
Thank you! :100:

**Pull request merged**
