### PR TITLE
Long factorial

### PR DESCRIPTION
**Pull request by Manikant25**
## Related Issue
Solved issue number: #27 

### Describe the changes you've made
Added code for calculating the factorial of a large number using C++. I used an array to store the factorial result as in C++ it's difficult because the long long int datatype can store max of 18 digits.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Have you checked your code? Your code is giving wrong answer.

**Comment by Manikant25** [comment]
At which test case, I checked and ran for **0,1,6,100**. It is working fine.

**Comment by Nivedita967** [comment]
Check by running it on Hackerrank, if it passes all the test cases then it is right.

**Comment by Manikant25** [comment]
Screenshot (506)
Passed all test cases on hackerrank

**Comment by Nivedita967** [comment]
Oh, Okay @Manikant25 :)

**Pull request merged**
