### PR TITLE
Solved Push Dominoes(Java and C++) and Best time to buy and sell stock(Java)

### PR DESCRIPTION
**Pull request by greenblade29**
Related Issue
  - This pull request contains solved solutions for Push Dominoes question from LeetCode and Best time to buy and sell stock question from LeetCode

Solved: #175,  #221

Describe the changes you've made
I have uploaded two files in the Leetcode directory that contain solution for Push Dominoes question and Best time to buy and sell stock question

Language used for coding
Java, C++

Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
You have added "best time to buy and sell stock" problem also?

**Comment by greenblade29** [comment]
> You have added "best time to buy and sell stock" problem also?

All of them are in the same branch :/ .... that's what I was telling you earlier

**Comment by Nivedita967** [comment]
That is why working in different branch other than main is best.

**Comment by greenblade29** [comment]
> That is why working in different branch other than main is best.

Okay, I will create different branches from now on 👍🏻

**Pull request merged**
