### PR TITLE
Create spare-arrays.cpp

### PR DESCRIPTION
**Pull request by Ayush7614**
## Related Issue
Solved issue number: #474 

### Describe the changes you've made
Added solution of spare arrays 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Ayush7614** [comment]
This pull is for #474  issue plss review it @Nivedita967

**Comment by Ayush7614** [comment]
@Nivedita967 plss review it

**Comment by Nivedita967** [comment]
Add comments to your code.

**Comment by Ayush7614** [comment]
@Nivedita967 now you can review it

**Comment by Ayush7614** [comment]
@Nivedita967 plss review it

**Comment by Nivedita967** [comment]
@Ayush7614 Problem name is "Sparse Arrays". You have written "Spare Arrays" in your folder and file name.

**Comment by Ayush7614** [comment]
@Nivedita967 now you can review it

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
