### PR TITLE
Added solution to the for loop problem on hackerrank in cpp

### PR DESCRIPTION
**Pull request by msbuddhu**
## Related Issue
Solved issue number: **630**

### Describe the changes you've made
Added solution to the for loop problem on hackerrank in cpp

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Hey @msbuddhu Mention your issue number that you have solved.

**Comment by msbuddhu** [comment]
My issue number is **#630**

**Comment by Nivedita967** [comment]
No, this is your pull request number. Mention the issue number in which you are assigned to do this work.

**Comment by msbuddhu** [comment]
Please help me. I can't find the issue number.

**Comment by Nivedita967** [comment]
Have you assigned to any issue ?

**Comment by msbuddhu** [comment]
No.

**Comment by Nivedita967** [comment]
That's why. [See this](https://github.com/Nivedita967/Data-Structure-and-Algorithms/issues/21#issue-807087018)

**Comment by Nivedita967** [comment]
Get yourself assigned first to the issue on which you want to work.

**Pull request closed without merging**
