### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by kmryashasvi**
## Related Issue
Solved issue number: #638

### Describe the changes you've made
1. Added badges in the same requested by the mentor.
2. Modified 1st line of the readme file (I can undo it if you want)
3. Heading of the repo is center aligned on the readme file

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
MD+HTML

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by kmryashasvi** [comment]
Feel free to interrupt me if you need some modification

**Comment by Nivedita967** [comment]
You have not closed the h1 tag.

**Comment by kmryashasvi** [comment]
Done

**Comment by Nivedita967** [comment]
Open source badge should be in center for better look, isn't it ?

**Comment by kmryashasvi** [comment]
Yes, you are right, it will be better in the middle
But alignment of badges is not possible,
Let me try once

**Comment by kmryashasvi** [comment]
> Open source badge should be in center for better look, isn't it ?

I have put the open source badge in the middle of the second row, is that what you wanted?

**Comment by Nivedita967** [comment]
Revert the changes. Don't center it.

**Comment by Nivedita967** [comment]
contributors, Maintenance, Open Source tags are still in the next line.

**Comment by kmryashasvi** [comment]
> contributors, Maintenance, Open Source tags are still in the next line.

because they are unable to be wrapped in the same line,
we have to remove some badges if we want to put them in one line

**Comment by Nivedita967** [comment]
> > contributors, Maintenance, Open Source tags are still in the next line.
> 
> because they are unable to be wrapped in the same line,
> we have to remove some badges if we want to put them in one line

Just remove your br tag there and add open source tag under contributing section.

**Comment by kmryashasvi** [comment]
Then it becomes like this, is it okay?
image

**Comment by Nivedita967** [comment]
Add open source tag under contributing section.

**Comment by kmryashasvi** [comment]
you mean contributing section?
image

**Comment by Nivedita967** [comment]
> you mean contributing section?
> image

yes

**Comment by kmryashasvi** [comment]
Done

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
