### PR TITLE
Added AddTwoNumbers Problem in python

### PR DESCRIPTION
**Pull request by arbazalam01**
## Related Issue
Closes: #576 
### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Language used for coding
Mention the language you have used for coding here.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Your folder name should be same as problem name. Also add some comments to your code.
Please read [Contribution Guidelines](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/.github/contributing.md)

**Comment by arbazalam01** [comment]
can you please review the PR

**Comment by Nivedita967** [comment]
I have requested you changes, please check your file according to requirement.

**Comment by arbazalam01** [comment]
Now can you please check

**Review by Nivedita967 — CHANGES_REQUESTED** [review]
Please add some comments to code so that beginner can understand it easily.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
