### PR TITLE
added Minimum distance.c

### PR DESCRIPTION
**Pull request by UG-SEP**
## Related Issue
Closes: #1251 

### Describe the changes you've made
Added minimum distance.c program

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Language used for coding
C language 

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
@UG-SEP If you have documented your code and checked it locally, then check last two checkboxes also. Check all the checkboxes :)

**Comment by Nivedita967** [comment]
@UG-SEP  Have you run your code at Hackerrank? 
You are printing some extra sentences, so test cases will not pass. Correct them please.

**Comment by UG-SEP** [comment]
> @UG-SEP Have you run your code at Hackerrank?
> You are printing some extra sentences, so test cases will not pass. Correct them, please.

yes @Nivedita967   I know it runs all test case but after that, I add some extra text to provide a user interface but if you want I can remove them

**Comment by Nivedita967** [comment]
> > @UG-SEP Have you run your code at Hackerrank?
> > You are printing some extra sentences, so test cases will not pass. Correct them, please.
> 
> yes @Nivedita967 I know it runs all test case but after that, I add some extra text to provide a user interface but if you want I can remove them

Okay, that was intentionally, then no problem :)

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
