### PR TITLE
"Added solution to Minimze the Heights II"

### PR DESCRIPTION
**Pull request by Apurva-tech**
## Related Issue
NA

### Describe the changes you've made
Added solution to a problem from GeeksofGeeks, named Minimize the Heights II. Given an array of integers H representing heights of towers and a positive integer B. It is allowed to either increase or decrease the height of every tower by B (only once).

How to calculate the minimum possible difference between the heights of the longest and the shortest tower after modifications.

Note: It is mandatory to either increase or decreases the height of every tower.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Are you contributing under "Cross Winter of Code" ?

**Comment by Apurva-tech** [comment]
> Are you contributing under the "Cross Winter of Code" program?

No ma'am, I have added a solution to a random question under DSA and arrays tag named: Minimize the Heights II.

**Comment by Nivedita967** [comment]
Oh great! Your code is nice, Just add some comments to your code so that beginners can understand it easily :)

**Comment by Nivedita967** [comment]
> Oh great! @Apurva-tech Your code is nice, Just add some comments to your code so that beginners can understand it easily :)

@Apurva-tech, please add some comments in your code.

**Pull request closed without merging**
