### PR TITLE
Daanish and Problems

### PR DESCRIPTION
**Pull request by jayantjethi**
Daanish and Problems

## Related Issue
Solved issue number: #599 

### Describe the changes you've made
Added a file for code of Daanish and Problems

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Hey, the problem name on platform is "Daanish and Problems". So change your folder name from `Danish And Problems` to `Daanish and Problems` .

**Comment by jayantjethi** [comment]
@Nivedita967 mam Now is it fine??

**Comment by Nivedita967** [comment]
I am asking to change folder name not the file name.

**Comment by jayantjethi** [comment]
@Nivedita967 mam now??

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
