### PR TITLE
Added config.yml file for Welcome Bot

### PR DESCRIPTION
**Pull request by m-code12**
## Issue that this pull request solves

 Closes: #127  

### What is the change?
Created config.yml file for the welcome bot to help first-time contributors. To activate the app you need to go to https://github.com/apps/welcome and click on install and give the app the required permissions  (Pull requests: Read & Write
Issues: Read & Write).

### How was it tested?
I have tested the welcome bot with the config.yml file in my personal repository. Here is a link to the repo:
https://github.com/m-code12/WelcomeBot

## Submissions guide:

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by Nivedita967** [comment]
Hey @m-code12 
Screenshot (126)
Is this for pull request ? You have written *very first issue* ?

**Comment by m-code12** [comment]
> Hey @m-code12
> Screenshot (126)
> Is this for pull request ? You have written _very first issue_ ?

That is by mistake, I'll change it.

**Comment by m-code12** [comment]
I have made the changes @Nivedita967

**Comment by Nivedita967** [comment]
Have you checked its working properly? (Just asking) 
This will start working just by merging this pull request ?

**Comment by m-code12** [comment]
> Have you checked its working properly? (Just asking)
> This will start working just by merging this pull request ?

To activate the app you need to go to https://github.com/apps/welcome and click on install and give the app the required permissions (Pull requests: Read & Write
Issues: Read & Write).

After this, it will be good to go.

**Comment by Nivedita967** [comment]
Please make one change, Code of Conduct path has been changed in this project.
Update the path in your code.

**Comment by m-code12** [comment]
> Please make one change, Code of Conduct path has been changed in this project.
> Update the path in your code.

Done

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
