### PR TITLE
Find Peak Element

### PR DESCRIPTION
**Pull request by Amit366**
## Related Issue
Closes: #775 

### Describe the changes you've made
Algorithm to find peak element

### Language used for coding
Java

### CODE REVIEW

**Review by Nivedita967 — CHANGES_REQUESTED** [review]
Here also remove extra file (.json)

**Comment by Amit366** [comment]
I have removed it

**Comment by Nivedita967** [comment]
It is also present in "Peak Element" file commit.

**Comment by Amit366** [comment]
But there is a delete Jason file commit.

**Comment by Amit366** [comment]
Now what should I do??

**Comment by Amit366** [comment]
@Nivedita967 when I am clicking to submit, it is showing 404 error

**Comment by Nivedita967** [comment]
> @Nivedita967 when I am clicking to submit, it is showing 404 error

Where you are submitting?

**Comment by Amit366** [comment]
Sorry not submitting, committing

**Comment by Nivedita967** [comment]
Screenshot (136)

This is your "Peak Element" commit.

**Comment by Amit366** [comment]
I will do one thing, I will close this and again open

**Pull request closed without merging**
