### PR TITLE
fix:added 1st question and its answer in c

### PR DESCRIPTION
**Pull request by kmryashasvi**

### CODE REVIEW

**Comment by Nivedita967** [comment]
Please change your file name to "Hello, World.c" so that identifying problem from HackerRank will be easy.

**Comment by kmryashasvi** [comment]
is it okay now?

**Comment by Nivedita967** [comment]
Nice @kmryashasvi .

**Comment by kmryashasvi** [comment]
@Nivedita967  then why aren't you merging it?
have a look at my repo
@sakshi-1604 @gitter-badger

**Comment by Nivedita967** [comment]
@kmryashasvi Keep Contributing.

**Pull request merged**
