### PR TITLE
Adding solution to Enormous Input Test (.py)

### PR DESCRIPTION
**Pull request by Jatin2020-24**
## Related Issue
Solved issue number: #206

### Describe the changes you've made
Added Solution to codechef problem "Enormous Input Test".

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Python3.6

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.
#https://github.com/Nivedita967/Data-Structure-and-Algorithms/issues/206#issuecomment-780656440

### CODE REVIEW

**Comment by Nivedita967** [comment]
You have documented your code also. So, check all the checkboxes.

**Comment by Jatin2020-24** [comment]
Please recheck, Now I have checked all the checkboxes #https://github.com/Nivedita967/Data-Structure-and-Algorithms/pull/279#issuecomment-781184039

**Comment by Jatin2020-24** [comment]
Please recheck, Now I checked all checkboxes #https://github.com/Nivedita967/Data-Structure-and-Algorithms/pull/279#issuecomment-781184039

**Comment by Nivedita967** [comment]
Now everything is Perfect. Nice work :)

**Pull request merged**
