### PR TITLE
Added source code for 'Recursive Digit Sum' problem in Java

### PR DESCRIPTION
**Pull request by abhinav5481**
## Related Issue
Closes: #810

### Describe the changes you've made
Added source code for 'Recursive Digit Sum' problem in Java

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Java

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

Please review my code.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Here your problem name is "Recursive Digit Sum" on Hackerrank. So just change your folder name to "Recursive Digit Sum".

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I have updated the folder name. Please review my PR

**Review by Nivedita967 — CHANGES_REQUESTED** [review]
Your folder name is still "Recursive digit sum". Change it to "Recursive Digit Sum".

**Comment by Nivedita967** [comment]
This time you have changed your file name.

**Comment by Nivedita967** [comment]
Change your directory name. Your directory name should be always same as the problem name as on platform.

**Comment by abhinav5481** [comment]
> Change your directory name. Your directory name should be always same as the problem name as on platform.

Yeah, Give me a minute. I'm amazed why the folder name & file name didn't change. I am correcting it.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I have updated the Folder  & file name.

**Review by Nivedita967 — APPROVED** [review]

**Pull request merged**
