### PR TITLE
Added-issue-template

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolve issue #24 .

### CODE REVIEW

**Comment by Nivedita967** [comment]
Hey @96RadhikaJadhav, Please add a simple issue template that just contains 
1. Problem Link (problem on which contributors want  to work) 
2. Coding Platform (from where contributors pick the problem)
3. And one "check list" that contributors have test the code or not.
 That's it.

**Comment by 96RadhikaJadhav** [comment]
@Nivedita967 I have added another issue template. Please have a look and let me know if any changes required.

**Comment by Nivedita967** [comment]
@96RadhikaJadhav This is still long. Please remove -
1. Describe the changes you've made ( because changes are not here, everyone is adding new documentation)
2. Test plan (not required)
3. In Checklist
> * Checklist 2
> * Checklist 4
> * Checklist 6
### You can add one section describing to mention language in which contributor wants to code.

**Comment by 96RadhikaJadhav** [comment]
@Nivedita967  I have made the changes and when trying to push it getting below error:
fatal: unable to access 'https://github.com/96RadhikaJadhav/Data-Structure-and-Algorithms.git/': Failed to connect to github.com port 443: Timed out
I searched a lot but not getting proper solution. Can you help me with this?

**Comment by Nivedita967** [comment]
Are you still getting this error or resolved ?

**Comment by 96RadhikaJadhav** [comment]
> Are you still getting this error or resolved ?

@Nivedita967  Resolved :) .

**Comment by Nivedita967** [comment]
That's Great :)

**Comment by Nivedita967** [comment]
Please remove checklists. Checklist is not at all required.
And keep heading of sections short, and describe below the heading about heading.

**Comment by 96RadhikaJadhav** [comment]
> Please remove checklists. Checklist is not at all required.
> And keep heading of sections short, and describe below the heading about heading.

@Nivedita967 Done.

**Comment by Nivedita967** [comment]
Some more changes are required. 
1. Please remove "Describe if there is any unusual behaviour of your code" section because contributor is not including code in the issue, so not required.
2. Under "Programming language" section, please include checklist for four language ( C, C++, Java and Python).

**Comment by 96RadhikaJadhav** [comment]
> Some more changes are required.
> 
> 1. Please remove "Describe if there is any unusual behaviour of your code" section because contributor is not including code in the issue, so not required.
> 2. Under "Programming language" section, please include checklist for four language ( C, C++, Java and Python).

Done.

**Comment by Nivedita967** [comment]
Mention in which programming language you want to code <- Please remove this in "Programming language" section.
And make heading one size large.

**Comment by 96RadhikaJadhav** [comment]
> `Mention in which programming language you want to code` <- Please remove this in "Programming language" section.
> And make heading one size large.

All the headings to make one size large or just programming language one?

**Comment by Nivedita967** [comment]
@96RadhikaJadhav Now this is great :)

**Pull request merged**
