### PR TITLE
Add Solution for Jumping On the Clouds C++ Hackerrank

### PR DESCRIPTION
**Pull request by deepesh101**
## Related Issue
Solved issue number: #109

### Describe the changes you've made
Added JumpingOnTheCouds.cpp, the solution of the problem from [Hackerrank](https://www.hackerrank.com/challenges/jumping-on-the-clouds/problem). The template of the code is the same as the one provided by Hackerrank.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
My code has passed all the test cases on Hackerrank. 

### Language used for coding
C++

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Please add some comments to your code for easy understanding for beginners.

**Comment by deepesh101** [comment]
Ok, for sure.

**Comment by deepesh101** [comment]
Added comments, please review.

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
