### PR TITLE
new solution Path Sum added to leetcode

### PR DESCRIPTION
**Pull request by sakshi-1604**

### CODE REVIEW

**Comment by Nivedita967** [comment]
Why have you added .vs folder?

**Comment by sakshi-1604** [comment]
It got added by default ,as I was editing the file in vs(visual studio)
If you want I can delete that file

**Comment by Nivedita967** [comment]
> It got added by default ,as I was editing the file in vs(visual studio)
> If you want I can delete that file

Sure.

**Comment by sakshi-1604** [comment]
Hey, I have deleted .vs folder

**Comment by sakshi-1604** [comment]
you can take a look, if you want

**Comment by sakshi-1604** [comment]
If you want I can add more solutions of leetcode???

**Comment by Nivedita967** [comment]
> If you want I can add more solutions of leetcode???

sure, go for it.

**Comment by Nivedita967** [comment]
> If you want I can add more solutions of leetcode???

Sure you can, but you may open new pull request for those.

**Comment by sakshi-1604** [comment]
ok

**Comment by Nivedita967** [comment]
Thank You @sakshi-1604  
Keep Contributing :-)

**Pull request merged**
