### PR TITLE
Added solution of Positive Prefixes.

### PR DESCRIPTION
**Pull request by gh4abhi**
## Related Issue
#153 

### Describe the changes you've made
Added solution of Positive Prefixes.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
C++

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
Your comments in your code is very less, always try to maximize comments in your code for easy understanding of code.

**Comment by gh4abhi** [comment]
Ok.

**Comment by gh4abhi** [comment]
I will add more comments in my programs from the next time.

**Comment by Nivedita967** [comment]
Add comments to all your code, this pull request and all next pull request.

**Comment by gh4abhi** [comment]
Ok

**Comment by gh4abhi** [comment]
Please check it now.

**Comment by gh4abhi** [comment]
Please check it now.

**Pull request merged**
