### PR TITLE
Created palindrome_number in C++ language.

### PR DESCRIPTION
**Pull request by gopichandpuli9**

### CODE REVIEW

**Comment by Nivedita967** [comment]
Issue number?

**Comment by gopichandpuli9** [comment]
#95

**Comment by Nivedita967** [comment]
Two issue in one pull request?

**Comment by gopichandpuli9** [comment]
Yeah!! Shouldn't do that?

**Comment by Nivedita967** [comment]
No, Try to create separate pull request.

**Comment by Nivedita967** [comment]
Add your code in the respective folder, add your code file with proper format
(Leetcode/Palindrome Number/Palindrome_Number.py)
Similarly for trailing zeroes of a factorial.
Also add comments to your code.

**Pull request closed without merging**
