### PR TITLE
Burst ballon.c

### PR DESCRIPTION
**Pull request by Amit366**
## Related Issue
Solved issue number: #85 

### Describe the changes you've made
Burst balloon algorithm using C

### Language used for coding
C

### CODE REVIEW

**Comment by Nivedita967** [comment]
You have made so many changes ?

**Comment by Amit366** [comment]
@Nivedita967 what changes??

**Comment by Amit366** [comment]
I will send it again.

**Comment by Amit366** [comment]
@Nivedita967 I am getting error while cloning it. Thats why there are many changes

**Comment by Amit366** [comment]
error: invalid path 'Hackerrank/Snakes And Ladders /Snakes_and_ladders.java'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Nivedita967** [comment]
@Amit366 Please clone again, I have removed the error.

**Pull request closed without merging**
