### PR TITLE
Added source code to compare strings by frequency of smallest character

### PR DESCRIPTION
**Pull request by abhinav5481**
## Related Issue
Closes: #728 

### Describe the changes you've made
Added source code to compare strings by frequency of smallest character

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Language used for coding
Java

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

PLease review my code & let me know if any changes are required.

### CODE REVIEW

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I have added comments. Please review my code.

**Comment by Nivedita967** [comment]
Still your folder name is not correct. Problem name is "Compare Strings by Frequency of the Smallest Character".

**Review by Nivedita967 — COMMENTED** [review]
There are so many unwanted files added.

**Comment by abhinav5481** [comment]
Sorry for the inconvenience. I have removed those extra files & folders. Please review my code.

**Comment by Nivedita967** [comment]
Confirmed?

**Comment by abhinav5481** [comment]
> Confirm?

Yes

**Pull request merged**
