### PR TITLE
issue#424 : longest valid parentheses in python

### PR DESCRIPTION
**Pull request by Mansi3546**
## Related Issue
Solved issue number: #issue number that will be closed through this PR
issue #424 ::- longest valid parentheses in python

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Language used for coding
Mention the language you have used for coding here.
Python

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have documented the code.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Nivedita967** [comment]
@Mansi3546 Your code is giving some error.

**Comment by Mansi3546** [comment]
> @Mansi3546 Your code is giving some error.

@Nivedita967 .. no didi,.. I think.. it's working fine,.. there is no error.
see,.. [https://py3.codeskulptor.org/#user306_NtZKnOvOTDAkX72.py]

**Comment by Nivedita967** [comment]
Your code should run on leetcode - https://leetcode.com/problems/longest-valid-parentheses/

**Comment by Mansi3546** [comment]
> Your code should run on leetcode - https://leetcode.com/problems/longest-valid-parentheses/

oh...ya.. It was just because in Leetcode ..there is necessity of "Solution" class,.. I fix that issue and now,.. It will work fine in Leetcode too.

**Comment by Nivedita967** [comment]
Nice :)

**Pull request merged**
